---
title: "BIS015L Project"
authors: "Chloe, Emily, Ibrahim"
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: spacelab
    keep_md: yes
---

## Load Libraries 

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(albersusa)
library(ggmap)
library(svglite)
library(shiny)
library(shinydashboard)
options(scipen=999)
``` 

## Load the Data
```{r}
disease <- readr::read_csv("Data/infectious-diseases-by-county-year-and-sex 2.csv")
disease
```

## Tidy Names of Data
```{r}
disease_tidy <- janitor::clean_names(disease)
names(disease_tidy)
```

## Remove data we will not use
```{r}
disease_data <- disease_tidy %>% 
  select(disease, county, year, sex, cases, population)
disease_data
```

## Summary of Data

```{r}
skimr::skim(disease_data)
```

```{r}
dim(disease_data)
```

```{r}
naniar::miss_var_summary(disease_data)
```


## Uploading California County Map

```{r}
us_comp <- usa_sf()
cnty_comp <- counties_sf()
ca_comp <- us_comp %>% 
  filter(name=="California")
ca_comp <- us_comp %>% 
  filter(name=="California")
ca_cnty_comp <- cnty_comp %>% 
  filter(state=="California")
```


```{r}
cali_map <- ggplot() +
  geom_sf(data = ca_comp, size = 0.125)+
  geom_sf(data = ca_cnty_comp, size = 0.125)
```

## Shiny App Stuff

```{r}
# if (!require("tidyverse")) install.packages('tidyverse')
```

```{r}
disease_data$cases <- as.numeric(disease_data$cases) 
disease_data$disease <- as.factor(disease_data$disease) 
```

```{r}
disease_data %>% 
  filter(couunty!="California") %>% 
  filter(disease=="Amebiasis") %>% 
  ggplot(aes(x=county, y=cases))+
  geom_col()
```


```{r}
ui <- dashboardPage(skin="purple",
  dashboardHeader(title = "Disease Abundance"),
  dashboardSidebar(disable = T),
  dashboardBody(
  fluidRow(
  box(title = "Plot Options", width = 3,
  selectInput("fill", "Select Disease", choices=unique(disease_data$disease)),
                # c("Amebiasis", "Anaplasmosis", "Anthrax", "Babesiosis", "Botulism, Foodborne", "Botulism, Other", "Botulism, Wound", "Brucellosis", "Campylobacteriosis", "Chikungunya Virus Infection", "Cholera", "Ciguatera Fish Poisoning", "Coccidioidomycosis", "Creutzfeldt-Jakob Disease and other Transmissible Spongiform Encephalopathies", "Cryptosporidiosis", "Cyclosporiasis", "Cysticercosis or Taeniasis", "Dengue", "Domoic Acid Poisoning", "Ehrlichiosis", "Flavivirus Infection of Undetermined Species", "Giardiasis", "Hantavirus Infection", "Hemolytic Uremic Syndrome", "Hepatitis E", "acute infection", "Legionellosis", "Leprosy", "Leptospirosis", "Listeriosis", "Lyme Disease", "Malaria", "Paralytic Shellfish Poisoning", "Paratyphoid Fever","Plague, human", "Psittacosis", "Q Fever", "Rabies, human", "Relapsing Fever", "Salmonellosis", "Scombroid Fish Poisoning", "Shiga toxin-producing E. coli (STEC) with HUS", "Shiga toxin-producing E. coli (STEC) without HUS", "Shigellosis", "Spotted Fever Rickettsiosis", "Streptococcal Infection (cases in food and dairy workers)", "Trichinosis", "Tularemia", "Typhoid Fever, case", "Typhus Fever", "Vibrio Infection (non-Cholera)", "Yellow Fever", "Yersiniosis", "Zika Virus Infection"), 
             #selected = "Amebiasis"),
      hr(),
      helpText("The data represent cases with an estimated illness onset date from 2001 through the last year indicated from California Confidential Morbidity Reports and/or Laboratory Reports")
  ),
  
  box(title = "Disease Abundance", width = 9,
  plotOutput("plot", width = "1200px", height = "500px", click="plot_click"),
  verbatimTextOutput("info")
  ) 
  ) 
  )
  ) 

server <- function(input, output, session) { 
  
  output$plot <- renderPlot({
  disease_data %>% 
  filter(county!="California", disease==input$fill, cases=="total") %>% 
  ggplot(aes_string(x = "county", y="cases", fill="input$fill")) + 
  geom_col()+
  theme_light(base_size = 18)+
  labs (x="County", y="Cases", fill="Disease")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), legend.position="none")
  })

  
   output$info <- renderText({
    paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
})
  session$onSessionEnded(stopApp)
  
} 
shinyApp(ui, server)
```

```{r}
ui <- dashboardPage(skin="purple",
  dashboardHeader(title = "Disease Abundance"),
  dashboardSidebar(disable = T),
  dashboardBody(
  fluidRow(
  box(title = "Plot Options", width = 3,
  selectInput("fill", "Select Fill", choices = 
                 c("county", "sex"), 
             selected = "county"),
      hr(),
      helpText("The data represent cases with an estimated illness onset date from 2001 through the last year indicated from California Confidential Morbidity Reports and/or Laboratory Reports")
  ),
  
  box(title = "Disease Abundance", width = 9,
  plotOutput("plot", width = "1200px", height = "500px", click="plot_click"),
  verbatimTextOutput("info")
  ) 
  ) 
  )
  ) 

server <- function(input, output, session) { 
  
  output$plot <- renderPlot({
  final_disease_data %>% 
  filter(county!="California") %>% 
  ggplot(aes_string(x = "disease", y="cases", fill="input$fill")) + 
  geom_col()+
  theme_light(base_size = 18)+
  labs (x="Disease", y="Cases", fill="Selected Fill")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), legend.position="none")
  })

  
   output$info <- renderText({
    paste0("x=", input$plot_click$x, "\ny=", input$plot_click$y)
})
  session$onSessionEnded(stopApp)
  
} 
shinyApp(ui, server)
```